# Generated by Django 4.0.3 on 2022-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('cuisine', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
