# Generated by Django 4.0.3 on 2022-04-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_hotel_created_hotel_updated_alter_hotel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('-created',)},
        ),
    ]
